.include "macro.inc"

.set noat
.set noreorder

.section .data, "wa"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel func_800A83F0
    /* 83F0 800A83F0 000080C8 */  lwc2       $0, 0x0($a0)
    /* 83F4 800A83F4 040081C8 */  lwc2       $1, 0x4($a0)
    /* 83F8 800A83F8 080082C8 */  lwc2       $2, 0x8($a0)
    /* 83FC 800A83FC 0C0083C8 */  lwc2       $3, 0xC($a0)
    /* 8400 800A8400 100084C8 */  lwc2       $4, 0x10($a0)
    /* 8404 800A8404 140085C8 */  lwc2       $5, 0x14($a0)
    /* 8408 800A8408 00000000 */  nop
    /* 840C 800A840C 00000000 */  nop
    /* 8410 800A8410 3000284A */  rtpt
    /* 8414 800A8414 0000ACE8 */  swc2       $12, 0x0($a1)
    /* 8418 800A8418 0400ADE8 */  swc2       $13, 0x4($a1)
    /* 841C 800A841C 0800AEE8 */  swc2       $14, 0x8($a1)
    /* 8420 800A8420 18000834 */  ori        $t0, $zero, 0x18
    /* 8424 800A8424 0C000934 */  ori        $t1, $zero, 0xC
    /* 8428 800A8428 20208800 */  add        $a0, $a0, $t0 /* handwritten instruction */
    /* 842C 800A842C 2028A900 */  add        $a1, $a1, $t1 /* handwritten instruction */
    /* 8430 800A8430 000080C8 */  lwc2       $0, 0x0($a0)
    /* 8434 800A8434 040081C8 */  lwc2       $1, 0x4($a0)
    /* 8438 800A8438 080082C8 */  lwc2       $2, 0x8($a0)
    /* 843C 800A843C 0C0083C8 */  lwc2       $3, 0xC($a0)
    /* 8440 800A8440 100084C8 */  lwc2       $4, 0x10($a0)
    /* 8444 800A8444 140085C8 */  lwc2       $5, 0x14($a0)
    /* 8448 800A8448 00000000 */  nop
    /* 844C 800A844C 00000000 */  nop
    /* 8450 800A8450 3000284A */  rtpt
    /* 8454 800A8454 0000ACE8 */  swc2       $12, 0x0($a1)
    /* 8458 800A8458 0400ADE8 */  swc2       $13, 0x4($a1)
    /* 845C 800A845C 0800AEE8 */  swc2       $14, 0x8($a1)
    /* 8460 800A8460 18000834 */  ori        $t0, $zero, 0x18
    /* 8464 800A8464 0C000934 */  ori        $t1, $zero, 0xC
    /* 8468 800A8468 20208800 */  add        $a0, $a0, $t0 /* handwritten instruction */
    /* 846C 800A846C 2028A900 */  add        $a1, $a1, $t1 /* handwritten instruction */
    /* 8470 800A8470 000080C8 */  lwc2       $0, 0x0($a0)
    /* 8474 800A8474 040081C8 */  lwc2       $1, 0x4($a0)
    /* 8478 800A8478 080082C8 */  lwc2       $2, 0x8($a0)
    /* 847C 800A847C 0C0083C8 */  lwc2       $3, 0xC($a0)
    /* 8480 800A8480 100084C8 */  lwc2       $4, 0x10($a0)
    /* 8484 800A8484 140085C8 */  lwc2       $5, 0x14($a0)
    /* 8488 800A8488 00000000 */  nop
    /* 848C 800A848C 00000000 */  nop
    /* 8490 800A8490 3000284A */  rtpt
    /* 8494 800A8494 0000ACE8 */  swc2       $12, 0x0($a1)
    /* 8498 800A8498 0400ADE8 */  swc2       $13, 0x4($a1)
    /* 849C 800A849C 0800E003 */  jr         $ra
    /* 84A0 800A84A0 00000000 */   nop
.size func_800A83F0, . - func_800A83F0

glabel func_800A84A4
    /* 84A4 800A84A4 000080C8 */  lwc2       $0, 0x0($a0)
    /* 84A8 800A84A8 040081C8 */  lwc2       $1, 0x4($a0)
    /* 84AC 800A84AC 080082C8 */  lwc2       $2, 0x8($a0)
    /* 84B0 800A84B0 0C0083C8 */  lwc2       $3, 0xC($a0)
    /* 84B4 800A84B4 100084C8 */  lwc2       $4, 0x10($a0)
    /* 84B8 800A84B8 140085C8 */  lwc2       $5, 0x14($a0)
    /* 84BC 800A84BC 00000000 */  nop
    /* 84C0 800A84C0 00000000 */  nop
    /* 84C4 800A84C4 3000284A */  rtpt
    /* 84C8 800A84C8 0000ACE8 */  swc2       $12, 0x0($a1)
    /* 84CC 800A84CC 0400ADE8 */  swc2       $13, 0x4($a1)
    /* 84D0 800A84D0 0800AEE8 */  swc2       $14, 0x8($a1)
    /* 84D4 800A84D4 0800E003 */  jr         $ra
    /* 84D8 800A84D8 00000000 */   nop
.size func_800A84A4, . - func_800A84A4

/* Handwritten function */
glabel func_800A84DC
    /* 84DC 800A84DC 0C00878C */  lw         $a3, 0xC($a0)
    /* 84E0 800A84E0 0800868C */  lw         $a2, 0x8($a0)
    /* 84E4 800A84E4 0400858C */  lw         $a1, 0x4($a0)
    /* 84E8 800A84E8 0000848C */  lw         $a0, 0x0($a0)
    /* 84EC 800A84EC 0400E384 */  lh         $v1, 0x4($a3)
    /* 84F0 800A84F0 00000000 */  nop
  .L800A84F4:
    /* 84F4 800A84F4 000080C8 */  lwc2       $0, 0x0($a0)
    /* 84F8 800A84F8 040081C8 */  lwc2       $1, 0x4($a0)
    /* 84FC 800A84FC 0100184A */  rtps
    /* 8500 800A8500 00400A48 */  mfc2       $t2, $8 /* handwritten instruction */
    /* 8504 800A8504 080080C8 */  lwc2       $0, 0x8($a0)
    /* 8508 800A8508 0C0081C8 */  lwc2       $1, 0xC($a0)
    /* 850C 800A850C 0100184A */  rtps
    /* 8510 800A8510 00400B48 */  mfc2       $t3, $8 /* handwritten instruction */
    /* 8514 800A8514 100080C8 */  lwc2       $0, 0x10($a0)
    /* 8518 800A8518 140081C8 */  lwc2       $1, 0x14($a0)
    /* 851C 800A851C 0100184A */  rtps
    /* 8520 800A8520 0600404B */  nclip
    /* 8524 800A8524 00C00848 */  mfc2       $t0, $24 /* handwritten instruction */
    /* 8528 800A8528 00000000 */  nop
    /* 852C 800A852C 2F000005 */  bltz       $t0, .L800A85EC
    /* 8530 800A8530 2D00584B */   avsz3
    /* 8534 800A8534 00380F48 */  mfc2       $t7, $7 /* handwritten instruction */
    /* 8538 800A8538 00000000 */  nop
    /* 853C 800A853C 2B00E019 */  blez       $t7, .L800A85EC
    /* 8540 800A8540 2140E001 */   addu      $t0, $t7, $zero
    /* 8544 800A8544 00F00821 */  addi       $t0, $t0, -0x1000 /* handwritten instruction */
    /* 8548 800A8548 2800001D */  bgtz       $t0, .L800A85EC
    /* 854C 800A854C 0800ACE8 */   swc2      $12, 0x8($a1)
    /* 8550 800A8550 1000ADE8 */  swc2       $13, 0x10($a1)
    /* 8554 800A8554 1800AEE8 */  swc2       $14, 0x18($a1)
    /* 8558 800A8558 200086C8 */  lwc2       $6, 0x20($a0)
    /* 855C 800A855C 80780F00 */  sll        $t7, $t7, 2
    /* 8560 800A8560 2078E601 */  add        $t7, $t7, $a2 /* handwritten instruction */
    /* 8564 800A8564 00000000 */  nop
    /* 8568 800A8568 1000784A */  dpcs
    /* 856C 800A856C 00408B48 */  mtc2       $t3, $8 /* handwritten instruction */
    /* 8570 800A8570 1C0086C8 */  lwc2       $6, 0x1C($a0)
    /* 8574 800A8574 1400B6E8 */  swc2       $22, 0x14($a1)
    /* 8578 800A8578 00000000 */  nop
    /* 857C 800A857C 1000784A */  dpcs
    /* 8580 800A8580 00408A48 */  mtc2       $t2, $8 /* handwritten instruction */
    /* 8584 800A8584 180086C8 */  lwc2       $6, 0x18($a0)
    /* 8588 800A8588 0C00B6E8 */  swc2       $22, 0xC($a1)
    /* 858C 800A858C 00000000 */  nop
    /* 8590 800A8590 1000784A */  dpcs
    /* 8594 800A8594 00B00E48 */  mfc2       $t6, $22 /* handwritten instruction */
    /* 8598 800A8598 00000000 */  nop
    /* 859C 800A859C 0400AEA0 */  sb         $t6, 0x4($a1)
    /* 85A0 800A85A0 0400AEAC */  sw         $t6, 0x4($a1)
    /* 85A4 800A85A4 0000E98D */  lw         $t1, 0x0($t7)
    /* 85A8 800A85A8 0000A88C */  lw         $t0, 0x0($a1)
    /* 85AC 800A85AC 21582001 */  addu       $t3, $t1, $zero
    /* 85B0 800A85B0 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 85B4 800A85B4 24400101 */  and        $t0, $t0, $at
    /* 85B8 800A85B8 FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 85BC 800A85BC FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 85C0 800A85C0 24482101 */  and        $t1, $t1, $at
    /* 85C4 800A85C4 25500901 */  or         $t2, $t0, $t1
    /* 85C8 800A85C8 0000AAAC */  sw         $t2, 0x0($a1)
    /* 85CC 800A85CC FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 85D0 800A85D0 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 85D4 800A85D4 2428A100 */  and        $a1, $a1, $at
    /* 85D8 800A85D8 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 85DC 800A85DC 24586101 */  and        $t3, $t3, $at
    /* 85E0 800A85E0 2550AB00 */  or         $t2, $a1, $t3
    /* 85E4 800A85E4 0000EAAD */  sw         $t2, 0x0($t7)
    /* 85E8 800A85E8 1C00A520 */  addi       $a1, $a1, 0x1C /* handwritten instruction */
  .L800A85EC:
    /* 85EC 800A85EC 24008420 */  addi       $a0, $a0, 0x24 /* handwritten instruction */
    /* 85F0 800A85F0 FFFF6320 */  addi       $v1, $v1, -0x1 /* handwritten instruction */
    /* 85F4 800A85F4 BFFF0314 */  bne        $zero, $v1, .L800A84F4
    /* 85F8 800A85F8 2110A000 */   addu      $v0, $a1, $zero
    /* 85FC 800A85FC 0800E003 */  jr         $ra
    /* 8600 800A8600 00000000 */   nop
.size func_800A84DC, . - func_800A84DC

/* Handwritten function */
glabel func_800A8604
    /* 8604 800A8604 0C00878C */  lw         $a3, 0xC($a0)
    /* 8608 800A8608 0800868C */  lw         $a2, 0x8($a0)
    /* 860C 800A860C 0400858C */  lw         $a1, 0x4($a0)
    /* 8610 800A8610 0000848C */  lw         $a0, 0x0($a0)
    /* 8614 800A8614 0400E384 */  lh         $v1, 0x4($a3)
    /* 8618 800A8618 00000000 */  nop
  .L800A861C:
    /* 861C 800A861C 000080C8 */  lwc2       $0, 0x0($a0)
    /* 8620 800A8620 040081C8 */  lwc2       $1, 0x4($a0)
    /* 8624 800A8624 0100184A */  rtps
    /* 8628 800A8628 00400A48 */  mfc2       $t2, $8 /* handwritten instruction */
    /* 862C 800A862C 080080C8 */  lwc2       $0, 0x8($a0)
    /* 8630 800A8630 0C0081C8 */  lwc2       $1, 0xC($a0)
    /* 8634 800A8634 0100184A */  rtps
    /* 8638 800A8638 00400B48 */  mfc2       $t3, $8 /* handwritten instruction */
    /* 863C 800A863C 100080C8 */  lwc2       $0, 0x10($a0)
    /* 8640 800A8640 140081C8 */  lwc2       $1, 0x14($a0)
    /* 8644 800A8644 0100184A */  rtps
    /* 8648 800A8648 0600404B */  nclip
    /* 864C 800A864C 00C00848 */  mfc2       $t0, $24 /* handwritten instruction */
    /* 8650 800A8650 00000000 */  nop
    /* 8654 800A8654 31000005 */  bltz       $t0, .L800A871C
    /* 8658 800A8658 2D00584B */   avsz3
    /* 865C 800A865C 00380F48 */  mfc2       $t7, $7 /* handwritten instruction */
    /* 8660 800A8660 00000000 */  nop
    /* 8664 800A8664 02790F00 */  srl        $t7, $t7, 4
    /* 8668 800A8668 00000000 */  nop
    /* 866C 800A866C 2B00E019 */  blez       $t7, .L800A871C
    /* 8670 800A8670 2140E001 */   addu      $t0, $t7, $zero
    /* 8674 800A8674 00F00821 */  addi       $t0, $t0, -0x1000 /* handwritten instruction */
    /* 8678 800A8678 2800001D */  bgtz       $t0, .L800A871C
    /* 867C 800A867C 0800ACE8 */   swc2      $12, 0x8($a1)
    /* 8680 800A8680 1000ADE8 */  swc2       $13, 0x10($a1)
    /* 8684 800A8684 1800AEE8 */  swc2       $14, 0x18($a1)
    /* 8688 800A8688 200086C8 */  lwc2       $6, 0x20($a0)
    /* 868C 800A868C 80780F00 */  sll        $t7, $t7, 2
    /* 8690 800A8690 2078E601 */  add        $t7, $t7, $a2 /* handwritten instruction */
    /* 8694 800A8694 00000000 */  nop
    /* 8698 800A8698 1000784A */  dpcs
    /* 869C 800A869C 00408B48 */  mtc2       $t3, $8 /* handwritten instruction */
    /* 86A0 800A86A0 1C0086C8 */  lwc2       $6, 0x1C($a0)
    /* 86A4 800A86A4 1400B6E8 */  swc2       $22, 0x14($a1)
    /* 86A8 800A86A8 00000000 */  nop
    /* 86AC 800A86AC 1000784A */  dpcs
    /* 86B0 800A86B0 00408A48 */  mtc2       $t2, $8 /* handwritten instruction */
    /* 86B4 800A86B4 180086C8 */  lwc2       $6, 0x18($a0)
    /* 86B8 800A86B8 0C00B6E8 */  swc2       $22, 0xC($a1)
    /* 86BC 800A86BC 00000000 */  nop
    /* 86C0 800A86C0 1000784A */  dpcs
    /* 86C4 800A86C4 00B00E48 */  mfc2       $t6, $22 /* handwritten instruction */
    /* 86C8 800A86C8 00000000 */  nop
    /* 86CC 800A86CC 0400AEA0 */  sb         $t6, 0x4($a1)
    /* 86D0 800A86D0 0400AEAC */  sw         $t6, 0x4($a1)
    /* 86D4 800A86D4 0000E98D */  lw         $t1, 0x0($t7)
    /* 86D8 800A86D8 0000A88C */  lw         $t0, 0x0($a1)
    /* 86DC 800A86DC 21582001 */  addu       $t3, $t1, $zero
    /* 86E0 800A86E0 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 86E4 800A86E4 24400101 */  and        $t0, $t0, $at
    /* 86E8 800A86E8 FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 86EC 800A86EC FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 86F0 800A86F0 24482101 */  and        $t1, $t1, $at
    /* 86F4 800A86F4 25500901 */  or         $t2, $t0, $t1
    /* 86F8 800A86F8 0000AAAC */  sw         $t2, 0x0($a1)
    /* 86FC 800A86FC FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 8700 800A8700 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 8704 800A8704 2428A100 */  and        $a1, $a1, $at
    /* 8708 800A8708 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 870C 800A870C 24586101 */  and        $t3, $t3, $at
    /* 8710 800A8710 2550AB00 */  or         $t2, $a1, $t3
    /* 8714 800A8714 0000EAAD */  sw         $t2, 0x0($t7)
    /* 8718 800A8718 1C00A520 */  addi       $a1, $a1, 0x1C /* handwritten instruction */
  .L800A871C:
    /* 871C 800A871C 24008420 */  addi       $a0, $a0, 0x24 /* handwritten instruction */
    /* 8720 800A8720 FFFF6320 */  addi       $v1, $v1, -0x1 /* handwritten instruction */
    /* 8724 800A8724 BDFF0314 */  bne        $zero, $v1, .L800A861C
    /* 8728 800A8728 2110A000 */   addu      $v0, $a1, $zero
    /* 872C 800A872C 0800E003 */  jr         $ra
    /* 8730 800A8730 00000000 */   nop
.size func_800A8604, . - func_800A8604

/* Handwritten function */
glabel func_800A8734
    /* 8734 800A8734 000080C8 */  lwc2       $0, 0x0($a0)
    /* 8738 800A8738 040081C8 */  lwc2       $1, 0x4($a0)
    /* 873C 800A873C 0100184A */  rtps
    /* 8740 800A8740 00400A48 */  mfc2       $t2, $8 /* handwritten instruction */
    /* 8744 800A8744 080080C8 */  lwc2       $0, 0x8($a0)
    /* 8748 800A8748 0C0081C8 */  lwc2       $1, 0xC($a0)
    /* 874C 800A874C 0100184A */  rtps
    /* 8750 800A8750 00400B48 */  mfc2       $t3, $8 /* handwritten instruction */
    /* 8754 800A8754 100080C8 */  lwc2       $0, 0x10($a0)
    /* 8758 800A8758 140081C8 */  lwc2       $1, 0x14($a0)
    /* 875C 800A875C 0100184A */  rtps
    /* 8760 800A8760 0600404B */  nclip
    /* 8764 800A8764 00C00848 */  mfc2       $t0, $24 /* handwritten instruction */
    /* 8768 800A8768 00000000 */  nop
    /* 876C 800A876C 2C000005 */  bltz       $t0, .L800A8820
    /* 8770 800A8770 2D00584B */   avsz3
    /* 8774 800A8774 00380F48 */  mfc2       $t7, $7 /* handwritten instruction */
    /* 8778 800A8778 00000000 */  nop
    /* 877C 800A877C 2800E019 */  blez       $t7, .L800A8820
    /* 8780 800A8780 2170E001 */   addu      $t6, $t7, $zero
    /* 8784 800A8784 60F0CE21 */  addi       $t6, $t6, -0xFA0 /* handwritten instruction */
    /* 8788 800A8788 2500C01D */  bgtz       $t6, .L800A8820
    /* 878C 800A878C 0800ACE8 */   swc2      $12, 0x8($a1)
    /* 8790 800A8790 1000ADE8 */  swc2       $13, 0x10($a1)
    /* 8794 800A8794 1800AEE8 */  swc2       $14, 0x18($a1)
    /* 8798 800A8798 200086C8 */  lwc2       $6, 0x20($a0)
    /* 879C 800A879C 80780F00 */  sll        $t7, $t7, 2
    /* 87A0 800A87A0 2078E601 */  add        $t7, $t7, $a2 /* handwritten instruction */
    /* 87A4 800A87A4 1000784A */  dpcs
    /* 87A8 800A87A8 1C0086C8 */  lwc2       $6, 0x1C($a0)
    /* 87AC 800A87AC 1400B6E8 */  swc2       $22, 0x14($a1)
    /* 87B0 800A87B0 00408B48 */  mtc2       $t3, $8 /* handwritten instruction */
    /* 87B4 800A87B4 1000784A */  dpcs
    /* 87B8 800A87B8 180086C8 */  lwc2       $6, 0x18($a0)
    /* 87BC 800A87BC 0C00B6E8 */  swc2       $22, 0xC($a1)
    /* 87C0 800A87C0 00408A48 */  mtc2       $t2, $8 /* handwritten instruction */
    /* 87C4 800A87C4 1000784A */  dpcs
    /* 87C8 800A87C8 00B00E48 */  mfc2       $t6, $22 /* handwritten instruction */
    /* 87CC 800A87CC 00000000 */  nop
    /* 87D0 800A87D0 0400AEA0 */  sb         $t6, 0x4($a1)
    /* 87D4 800A87D4 0400AEAC */  sw         $t6, 0x4($a1)
    /* 87D8 800A87D8 0000E98D */  lw         $t1, 0x0($t7)
    /* 87DC 800A87DC 0000A88C */  lw         $t0, 0x0($a1)
    /* 87E0 800A87E0 21582001 */  addu       $t3, $t1, $zero
    /* 87E4 800A87E4 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 87E8 800A87E8 24400101 */  and        $t0, $t0, $at
    /* 87EC 800A87EC FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 87F0 800A87F0 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 87F4 800A87F4 24482101 */  and        $t1, $t1, $at
    /* 87F8 800A87F8 25500901 */  or         $t2, $t0, $t1
    /* 87FC 800A87FC 0000AAAC */  sw         $t2, 0x0($a1)
    /* 8800 800A8800 FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 8804 800A8804 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 8808 800A8808 2428A100 */  and        $a1, $a1, $at
    /* 880C 800A880C 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 8810 800A8810 24586101 */  and        $t3, $t3, $at
    /* 8814 800A8814 2550AB00 */  or         $t2, $a1, $t3
    /* 8818 800A8818 0000EAAD */  sw         $t2, 0x0($t7)
    /* 881C 800A881C 1C00A520 */  addi       $a1, $a1, 0x1C /* handwritten instruction */
  .L800A8820:
    /* 8820 800A8820 2110A000 */  addu       $v0, $a1, $zero
    /* 8824 800A8824 0800E003 */  jr         $ra
    /* 8828 800A8828 00000000 */   nop
.size func_800A8734, . - func_800A8734

/* Handwritten function */
glabel func_800A882C
    /* 882C 800A882C 000080C8 */  lwc2       $0, 0x0($a0)
    /* 8830 800A8830 040081C8 */  lwc2       $1, 0x4($a0)
    /* 8834 800A8834 0800E2C8 */  lwc2       $2, 0x8($a3)
    /* 8838 800A8838 0C00E3C8 */  lwc2       $3, 0xC($a3)
    /* 883C 800A883C 400084C8 */  lwc2       $4, 0x40($a0)
    /* 8840 800A8840 440085C8 */  lwc2       $5, 0x44($a0)
    /* 8844 800A8844 3000284A */  rtpt
    /* 8848 800A8848 2D00584B */  avsz3
    /* 884C 800A884C 00380F48 */  mfc2       $t7, $7 /* handwritten instruction */
    /* 8850 800A8850 00000000 */  nop
    /* 8854 800A8854 2E00E019 */  blez       $t7, .L800A8910
    /* 8858 800A8858 2170E001 */   addu      $t6, $t7, $zero
    /* 885C 800A885C 60F0CE21 */  addi       $t6, $t6, -0xFA0 /* handwritten instruction */
    /* 8860 800A8860 2B00C01D */  bgtz       $t6, .L800A8910
    /* 8864 800A8864 0800ACE8 */   swc2      $12, 0x8($a1)
    /* 8868 800A8868 1000ADE8 */  swc2       $13, 0x10($a1)
    /* 886C 800A886C 1800AEE8 */  swc2       $14, 0x18($a1)
    /* 8870 800A8870 4800E0C8 */  lwc2       $0, 0x48($a3)
    /* 8874 800A8874 4C00E1C8 */  lwc2       $1, 0x4C($a3)
    /* 8878 800A8878 0100184A */  rtps
    /* 887C 800A887C 2000AEE8 */  swc2       $14, 0x20($a1)
    /* 8880 800A8880 2C000E34 */  ori        $t6, $zero, 0x2C
    /* 8884 800A8884 80000D3C */  lui        $t5, (0x808080 >> 16)
    /* 8888 800A8888 8080AD35 */  ori        $t5, $t5, (0x808080 & 0xFFFF)
    /* 888C 800A888C 00308D48 */  mtc2       $t5, $6 /* handwritten instruction */
    /* 8890 800A8890 80780F00 */  sll        $t7, $t7, 2
    /* 8894 800A8894 2078E601 */  add        $t7, $t7, $a2 /* handwritten instruction */
    /* 8898 800A8898 1000784A */  dpcs
    /* 889C 800A889C 0400B6E8 */  swc2       $22, 0x4($a1)
    /* 88A0 800A88A0 0700AEA0 */  sb         $t6, 0x7($a1)
    /* 88A4 800A88A4 01780D3C */  lui        $t5, (0x78010000 >> 16)
    /* 88A8 800A88A8 2C000E3C */  lui        $t6, (0x2C001F >> 16)
    /* 88AC 800A88AC 1F00CE35 */  ori        $t6, $t6, (0x2C001F & 0xFFFF)
    /* 88B0 800A88B0 0C00ADAC */  sw         $t5, 0xC($a1)
    /* 88B4 800A88B4 1400AEAC */  sw         $t6, 0x14($a1)
    /* 88B8 800A88B8 001F0D34 */  ori        $t5, $zero, 0x1F00
    /* 88BC 800A88BC 1F1F0E34 */  ori        $t6, $zero, 0x1F1F
    /* 88C0 800A88C0 1C00ADAC */  sw         $t5, 0x1C($a1)
    /* 88C4 800A88C4 2400AEAC */  sw         $t6, 0x24($a1)
    /* 88C8 800A88C8 0000E98D */  lw         $t1, 0x0($t7)
    /* 88CC 800A88CC 0000A88C */  lw         $t0, 0x0($a1)
    /* 88D0 800A88D0 21582001 */  addu       $t3, $t1, $zero
    /* 88D4 800A88D4 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 88D8 800A88D8 24400101 */  and        $t0, $t0, $at
    /* 88DC 800A88DC FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 88E0 800A88E0 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 88E4 800A88E4 24482101 */  and        $t1, $t1, $at
    /* 88E8 800A88E8 25500901 */  or         $t2, $t0, $t1
    /* 88EC 800A88EC 0000AAAC */  sw         $t2, 0x0($a1)
    /* 88F0 800A88F0 FF00013C */  lui        $at, (0xFFFFFF >> 16)
    /* 88F4 800A88F4 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 88F8 800A88F8 2428A100 */  and        $a1, $a1, $at
    /* 88FC 800A88FC 00FF013C */  lui        $at, (0xFF000000 >> 16)
    /* 8900 800A8900 24586101 */  and        $t3, $t3, $at
    /* 8904 800A8904 2550AB00 */  or         $t2, $a1, $t3
    /* 8908 800A8908 0000EAAD */  sw         $t2, 0x0($t7)
    /* 890C 800A890C 2800A520 */  addi       $a1, $a1, 0x28 /* handwritten instruction */
  .L800A8910:
    /* 8910 800A8910 2110A000 */  addu       $v0, $a1, $zero
    /* 8914 800A8914 0800E003 */  jr         $ra
.size func_800A882C, . - func_800A882C
