package builder

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// https://raw.githubusercontent.com/encounter/objdiff/refs/heads/main/config.schema.json

type objdiffMetadata struct {
	Complete           bool     `json:"complete"`
	ReverseFnOrder     bool     `json:"reverse_fn_order"`
	SourcePath         string   `json:"source_path,omitempty"`
	ProgressCategories []string `json:"progress_categories,omitempty"`
	AutoGenerated      bool     `json:"auto_generated"`
}

type objdiffUnit struct {
	Name           string          `json:"name,omitempty"`
	Path           string          `json:"path,omitempty"`
	TargetPath     string          `json:"target_path,omitempty"`
	BasePath       string          `json:"base_path,omitempty"`
	ReverseFnOrder bool            `json:"reverse_fn_order"`
	Complete       bool            `json:"complete"`
	Metadata       objdiffMetadata `json:"metadata"`
}

type objdiffProgressCategory struct {
	ID   string `json:"id"`
	Name string `json:"name,omitempty"`
}

type objdiffConfig struct {
	CustomMake       string                    `json:"custom_make,omitempty"`
	BaseDir          string                    `json:"base_dir,omitempty"`
	BuildBase        bool                      `json:"build_base"`
	TargetDir        string                    `json:"target_dir,omitempty"`
	BuildTarget      bool                      `json:"build_target"`
	WatchPatterns    []string                  `json:"watch_patterns,omitempty"`
	IgnorePatterns   []string                  `json:"ignore_patterns,omitempty"`
	Units            []objdiffUnit             `json:"units,omitempty"`
	ProgressCategory []objdiffProgressCategory `json:"progress_categories,omitempty"`
}

// A segment name made only of digits, such as 17238, decodes as a number
// rather than a string, so accept both.
func segmentName(v any) string {
	switch n := v.(type) {
	case string:
		return n
	case uint64:
		return strconv.FormatUint(n, 10)
	case int64:
		return strconv.FormatInt(n, 10)
	case int:
		return strconv.Itoa(n)
	}
	return ""
}

type metaOverlay struct {
	id   string
	kind string
	name string
}

var metaCategories = map[string]string{
	"main":   "Game engine",
	"battle": "Battle",
	"field":  "Field",
	"menu":   "Menu",
	"world":  "World map",
	"mini":   "Minigame",
	"magic":  "Magic effect",
}

var metaOverlays = map[string]metaOverlay{
	"main":     {"main", "main", "Game engine"},

	"batini":   {"batini", "battle", "Battle init"},
	"batres":   {"batres", "battle", "Battle result"},
	"battle":   {"battle", "battle", "Battle"},
	"brom":     {"brom", "battle", "Battle ROM"},

	"dschange": {"dschange", "field", "Disc change"},
	"ending":   {"ending", "field", "Ending"},
	"field":    {"field", "field", "Field"},

	"bginmenu": {"bginmenu", "menu", "Background menu"},
	"cnfgmenu": {"cnfgmenu", "menu", "Config menu"},
	"savemenu": {"savemenu", "menu", "Save menu"},
	"itemmenu": {"itemmenu", "menu", "Item menu"},
	"world":    {"world", "world", "World map"},

	"chocobo":  {"chocobo", "mini", "Chocobo racing"},
	"jet":      {"jet", "mini", "jet"},

	"fire":     {"fire", "magic", "Fire"},
	"faira":    {"faira", "magic", "Fira"},
	"brizad":   {"brizad", "magic", "Blizzard"},
	"brizara":  {"brizara", "magic", "Blizzara"},
	"thunder":  {"thunder", "magic", "Thunder"},
	"thundera": {"thundera", "magic", "Thundara"},
	"barrier":  {"barrier", "magic", "Barrier"},
	"mabaria":  {"mabaria", "magic", "MBarrier"},
	"refrec":   {"refrec", "magic", "Reflect"},
	"lv5deth":  {"lv5deth", "magic", "LV.5 Death"},
	"choco0":   {"choco0", "magic", "choco0"},
}

func makeObjdiffConfig(b BuildConfig) objdiffConfig {
	var units []objdiffUnit
	var categories []objdiffProgressCategory
	kindCount := map[string]int{}
	for _, o := range b.Overlays {
		meta, ok := metaOverlays[o.Name]
		if !ok {
			panic(fmt.Sprintf("no metaOverlay entry for overlay %q", o.Name))
		}
		kindCount[meta.kind]++
	}
	seenKind := map[string]bool{}
	for _, o := range b.Overlays {
		meta := metaOverlays[o.Name]
		kindName, ok := metaCategories[meta.kind]
		if !ok {
			panic(fmt.Sprintf("no metaCategories entry for kind %q", meta.kind))
		}
		categoryID := meta.kind
		categoryName := kindName
		if kindCount[meta.kind] > 1 {
			categoryID = fmt.Sprintf("%s.%s", meta.kind, meta.id)
			categoryName = meta.name
			if !seenKind[meta.kind] {
				seenKind[meta.kind] = true
				categories = append(categories, objdiffProgressCategory{
					ID:   meta.kind,
					Name: kindName,
				})
			}
		}
		srcDir := filepath.Join(b.SrcPath, o.BasePath)
		asmDir := filepath.Join(b.AsmPath, o.BasePath)
		categories = append(categories, objdiffProgressCategory{
			ID:   categoryID,
			Name: categoryName,
		})
		for _, src := range o.Segments {
			if len(src) < 2 {
				continue
			}
			cat, ok := src[1].(string)
			if !ok {
				continue
			}
			name := ""
			if len(src) >= 3 {
				name = segmentName(src[2])
			}
			if name == "" {
				if v, ok := src[0].(uint64); ok {
					name = strconv.FormatInt(int64(v), 16)
					name = strings.ToUpper(name)
				}
			}
			if name == "" {
				panic("bug")
			}
			switch cat {
			case "c":
				srcFile := filepath.Join(srcDir, name+".c")
				objFile := filepath.Join(b.BuildPath, srcFile+".o")
				units = append(units, objdiffUnit{
					Name:       fmt.Sprintf("%s/%s", o.Name, name),
					BasePath:   objFile,
					TargetPath: targetPath(objFile),
					Metadata: objdiffMetadata{
						SourcePath:         srcFile,
						ProgressCategories: unitCategories(meta.kind, categoryID),
					},
				})
			case "hasm":
				srcFile := filepath.Join(srcDir, name+".s")
				objFile := filepath.Join(b.BuildPath, srcFile+".o")
				units = append(units, objdiffUnit{
					Name:       fmt.Sprintf("%s/%s", o.Name, name),
					BasePath:   objFile,
					TargetPath: targetPath(objFile),
					Metadata: objdiffMetadata{
						SourcePath:         srcFile,
						ProgressCategories: unitCategories(meta.kind, categoryID),
					},
				})
			case "data":
				fallthrough
			case "sbss":
				fallthrough
			case "bss":
				asmFile := filepath.Join(asmDir, "data", fmt.Sprintf("%s.%s.s", name, cat))
				objFile := filepath.Join(b.BuildPath, asmFile+".o")
				units = append(units, objdiffUnit{
					Name:       fmt.Sprintf("%s/%s_%s", o.Name, name, cat),
					BasePath:   objFile,
					TargetPath: targetPath(objFile),
					Metadata: objdiffMetadata{
						SourcePath:         asmFile,
						ProgressCategories: unitCategories(meta.kind, categoryID),
					},
				})
			}
		}
	}
	return objdiffConfig{
		CustomMake:  "ninja",
		BaseDir:     b.BuildPath,
		BuildBase:   true,
		TargetDir:   targetPath(b.BuildPath),
		BuildTarget: false,
		WatchPatterns: []string{
			"include/**.h",
			"src/**.c",
			"src/**.h",
			"src/**.s",
		},
		IgnorePatterns: []string{
			"build/**/*",
		},
		Units:            units,
		ProgressCategory: categories,
	}
}

func writeObjdiffConfig(b BuildConfig) error {
	data, err := json.Marshal(makeObjdiffConfig(b))
	if err != nil {
		return err
	}
	return os.WriteFile("objdiff.json", data, 0644)
}

func targetPath(path string) string {
	path = strings.Replace(path, "report/", "", 1)
	return filepath.Join("expected", path)
}

func unitCategories(kind, categoryID string) []string {
	if kind == categoryID {
		return []string{kind}
	}
	return []string{kind, categoryID}
}
