
typedef enum {
    BGM_NONE = 0x00,     // none
    BGM_NOTHING = 0x01,  // nothing
    BGM_OA = 0x02,       // Opening - Bombing Mission
    BGM_OB = 0x03,       // Bombing Mission
    BGM_DUN2 = 0x04,     // Chasing The Black-Caped Man
    BGM_GUITAR2 = 0x05,  // On The Other Side Of The Mountain
    BGM_FANFARE = 0x06,  // Fanfare (intro)
    BGM_MAKORO = 0x07,   // Mako Reactor
    BGM_BAT = 0x08,      // Fighting
    BGM_FIDDLE = 0x09,   // Fiddle De Chocobo
    BGM_KURAI = 0x0A,    // Anxious Heart
    BGM_CHU = 0x0B,      // Still More Fighting
    BGM_KETC = 0x0C,     // Cait Sith's Theme
    BGM_EARIS = 0x0D,    // Aerith's Theme
    BGM_TA = 0x0E,       // Final Fantasy VII Main Theme (World Map)
    BGM_TB = 0x0F,       // Final Fantasy VII Main Theme B
    BGM_SATO = 0x10,     // sato
    BGM_PARADE = 0x11,   // Rufus' Welcoming Ceremony
    BGM_COMICAL = 0x12,  // comical
    BGM_YUME = 0x13,     // Who Are You
    BGM_MATI = 0x14,     // Ahead on Our Way
    BGM_SIDO = 0x15,     // It's Difficult to Stand on Both Feet, Isn't It
    BGM_SIERA = 0x16,    // If You Open Your Heart
    BGM_WALZ = 0x17,     // Waltz de Chocobo
    BGM_CORNEO = 0x18,   // Don of the Slums
    BGM_HORROR = 0x19,   // Trail Of Blood
    BGM_CANYON = 0x1A,   // Cosmo Canyon
    BGM_RED = 0x1B,      // Red XIII's Theme
    BGM_SETO = 0x1C,     // Great Warrior
    BGM_AYASI = 0x1D,    // Lurking in the Darkness
    BGM_SINRA = 0x1E,    // Shinra Company
    BGM_SINRASLO = 0x1F, // Infiltrating Shinra Tower
    BGM_DOKUBO = 0x20,   // Underneath the Rotting Pizza
    BGM_BOKUJO = 0x21,   // Farm Boy
    BGM_TM = 0x22,       // On That Day, Five Years Ago
    BGM_TIFA = 0x23,     // Tifa's Theme
    BGM_COSTA = 0x24,    // Costa Del Sol
    BGM_ROCKET = 0x25,   // Oppressed People
    BGM_EARISLO = 0x26,  // Flowers Blooming in the Church
    BGM_CHASE = 0x27,    // Crazy Motorcycle
    BGM_RUKEI = 0x28,    // Sandy Badlands
    BGM_CEPHIROS = 0x29, // Those Chosen by the Planet
    BGM_BARRET = 0x2A,   // Barret's Theme
    BGM_COREL = 0x2B,    // Mining Town
    BGM_BOO = 0x2C,      // Life Stream
    BGM_ELEC = 0x2D,     // Electric de Chocobo
    BGM_RHYTHM = 0x2E,   // Turk's Theme
    BGM_FAN2 = 0x2F,     // Fanfare
    BGM_HIKU = 0x30,     // Highwind Takes To The Skies
    BGM_CANNON = 0x31,   // The Makou Cannon Is Fired ~ Shinra Explodes A
    BGM_DATE = 0x32,     // Interrupted By Fireworks
    BGM_CINTRO = 0x33,   // Those Chosen By The Planet (Intro)
    BGM_CINCO = 0x34,    // Cinco de Chocobo
    BGM_CHU2 = 0x35,     // J-E-N-O-V-A
    BGM_YUFI = 0x36,     // Descendant Of Shinobi
    BGM_ASERI = 0x37,    // Hurry!
    BGM_GOLD1 = 0x38,    // Gold Saucer
    BGM_MURA1 = 0x39,    // Parochial Town
    BGM_YADO = 0x3A,     // Good Night, Until Tomorrow
    BGM_OVER2 = 0x3B,    // Continue
    BGM_CRWIN = 0x3C,    // A Great Success
    BGM_CRLOST = 0x3D,   // Tango Of Tears
    BGM_ODDS = 0x3E,     // Racing Chocobo ~ Place Your Bets
    BGM_GEKI = 0x3F,     // Debut
    BGM_JUNON = 0x40,    // Off The Edge Of Despair
    BGM_TENDER = 0x41,   // Holding My Thoughts In My Heart
    BGM_WIND = 0x42,     // wind
    BGM_VINCENT = 0x43,  // The Nightmare's Beginning
    BGM_BEE = 0x44,      // Honeybee Manor
    BGM_JUKAI = 0x45,    // Forest Temple
    BGM_SADBAR = 0x46,   // Mark of the Traitor
    BGM_ASERI2 = 0x47,   // Hurry Faster!
    BGM_KITA = 0x48,     // The Great Northern Cave
    BGM_SID2 = 0x49,     // Cid's Theme
    BGM_SADSID = 0x4A,   // Sending a Dream Into the Universe
    BGM_ISEKI = 0x4B,    // You Can Hear the Cry of the Planet
    BGM_HEN = 0x4C,      // Who Am I
    BGM_UTAI = 0x4D,     // Utai
    BGM_SNOW = 0x4E,     // Buried in the Snow
    BGM_YUFI2 = 0x4F,    // Stolen Materia
    BGM_MEKYU = 0x50,    // Reunion
    BGM_CONDOR = 0x51,   // Fortress Of The Condor
    BGM_LB2 = 0x52,      // One-Winged Angel
    BGM_GUN = 0x53,      // Shinra Army Wages A Full-Scale Attack
    BGM_WEAPON = 0x54,   // Weapon Raid
    BGM_PJ = 0x55,       // Jenova Absolute
    BGM_SEA = 0x56,      // A Secret, Sleeping in the Deep Sea
    BGM_LD = 0x57,       // Judgment Day
    BGM_LB1 = 0x58,      // The Birth of God
    BGM_SENSUI = 0x59,   // sensui
    BGM_RO = 0x5A,       // The Countdown Begins
    BGM_JYRO = 0x5B,     // Steal The Tiny Bronco!
    BGM_NOINTRO = 0x5C,  // Those Chosen By The Planet (no intro)
    BGM_RIKU = 0x5D,     // The Makou Cannon Is Fired ~ Shinra Explodes B
    BGM_SI = 0x5E,       // The Makou Cannon Is Fired ~ Shinra Explodes C
    BGM_MOGU = 0x5F,     // Highwind Takes to the Skies
    BGM_PRE = 0x60,      // The Prelude
    BGM_FIN = 0x61,      // World Crisis
    BGM_HEART = 0x62,    // heart
    BGM_ROLL = 0x63,     // Staff Roll
} AkaoMusicTrack;
